/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yumu_admin_opencvjava_CameraPreview */

#ifndef _Included_com_yumu_admin_opencvjava_CameraPreview
#define _Included_com_yumu_admin_opencvjava_CameraPreview
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yumu_admin_opencvjava_CameraPreview
 * Method:    ImageProcessing
 * Signature: (II[B[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yumu_admin_opencvjava_CameraPreview_ImageProcessing
  (JNIEnv *, jobject, jint, jint, jbyteArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
