/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yumu_admin_opencvjava_MainActivity */

#ifndef _Included_com_yumu_admin_opencvjava_MainActivity
#define _Included_com_yumu_admin_opencvjava_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yumu_admin_opencvjava_MainActivity
 * Method:    framevideo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yumu_admin_opencvjava_MainActivity_framevideo
  (JNIEnv *, jobject);

/*
 * Class:     com_yumu_admin_opencvjava_MainActivity
 * Method:    capturevideo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yumu_admin_opencvjava_MainActivity_capturevideo
  (JNIEnv *, jobject);

/*
 * Class:     com_yumu_admin_opencvjava_MainActivity
 * Method:    main
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_yumu_admin_opencvjava_MainActivity_main
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
